export const mockTerritories = [
    {
        id: 1,
        name: "טריפולי",
        x: 63.0,
        y: 4.0,
        neighbors: [2, 3],
        soldiers: 1,
        owner: "computer",
        distanceFromComputerHQ: 1,
        distanceFromPlayerHQ: 6,
    },
    {
        id: 2,
        name: "ביירות",
        x: 50.8,
        y: 13.0,
        neighbors: [1, 4, 5],
        soldiers: 4,
        owner: "computer",
        headquarters: true,
        distanceFromComputerHQ: 0,
        distanceFromPlayerHQ: 6,
    },
    {
        id: 3,
        name: "בעלבכ",
        x: 70.3,
        y: 8.0,
        neighbors: [1, 5, 9],
        soldiers: 7,
        owner: "computer",
        distanceFromComputerHQ: 2,
        distanceFromPlayerHQ: 5,
    },
    {
        id: 4,
        name: "צידון",
        x: 48.8,
        y: 16.5,
        neighbors: [2, 5, 6, 7],
        soldiers: 6,
        owner: "computer",
        distanceFromComputerHQ: 1,
        distanceFromPlayerHQ: 5,
    },
    {
        id: 5,
        name: "זחלה",
        x: 62.5,
        y: 12.0,
        neighbors: [2, 3, 4, 6, 9],
        soldiers: 7,
        owner: "computer",
        distanceFromComputerHQ: 1,
        distanceFromPlayerHQ: 5,
    },
    {
        id: 6,
        name: "נבטיה",
        x: 53.7,
        y: 19.0,
        neighbors: [4, 5, 7, 8, 9],
        soldiers: 7,
        owner: "computer",
        distanceFromComputerHQ: 2,
        distanceFromPlayerHQ: 5,
    },
    {
        id: 7,
        name: "צור",
        x: 45.9,
        y: 21.0,
        neighbors: [4, 6, 8, 10],
        soldiers: 7,
        owner: "computer",
        distanceFromComputerHQ: 2,
        distanceFromPlayerHQ: 4,
    },
    {
        id: 8,
        name: "בינת ג׳בייל",
        x: 50.8,
        y: 23.5,
        neighbors: [6, 7, 9, 10],
        soldiers: 7,
        owner: "computer",
        distanceFromComputerHQ: 3,
        distanceFromPlayerHQ: 4,
    },
    {
        id: 9,
        name: "מרג׳ עיון",
        x: 60.5,
        y: 22.0,
        neighbors: [3, 5, 6, 8, 12],
        soldiers: 7,
        owner: "computer",
        distanceFromComputerHQ: 2,
        distanceFromPlayerHQ: 4,
    },
    {
        id: 10,
        name: "נהריה",
        x: 43.9,
        y: 35.2,
        neighbors: [7, 8, 11, 13],
        soldiers: 4,
        owner: "player",
        distanceFromComputerHQ: 3,
        distanceFromPlayerHQ: 3,
    },
    {
        id: 11,
        name: "צפת",
        x: 61.5,
        y: 31.9,
        neighbors: [10, 12, 13, 14],
        soldiers: 4,
        owner: "player",
        distanceFromComputerHQ: 4,
        distanceFromPlayerHQ: 3,
    },
    {
        id: 12,
        name: "קריית שמונה",
        x: 68.4,
        y: 27.3,
        neighbors: [9, 11, 14],
        soldiers: 4,
        owner: "player",
        distanceFromComputerHQ: 3,
        distanceFromPlayerHQ: 3,
    },
    {
        id: 13,
        name: "חיפה",
        x: 39.7,
        y: 41.3,
        neighbors: [10, 11, 15, 16],
        soldiers: 4,
        owner: "player",
        distanceFromComputerHQ: 4,
        distanceFromPlayerHQ: 2,
    },
    {
        id: 14,
        name: "טבריה",
        x: 66.4,
        y: 33.5,
        neighbors: [11, 12, 16],
        soldiers: 4,
        owner: "player",
        distanceFromComputerHQ: 4,
        distanceFromPlayerHQ: 2,
    },
    {
        id: 15,
        name: "נתניה",
        x: 34.2,
        y: 50.0,
        neighbors: [13, 18],
        soldiers: 4,
        owner: "player",
        distanceFromComputerHQ: 5,
        distanceFromPlayerHQ: 2,
    },
    {
        id: 16,
        name: "עפולה",
        x: 53.7,
        y: 40.4,
        neighbors: [13, 14, 17, 18],
        soldiers: 4,
        owner: "player",
        distanceFromComputerHQ: 5,
        distanceFromPlayerHQ: 1,
    },
    {
        id: 17,
        name: "ירושלים",
        x: 50.8,
        y: 56.6,
        neighbors: [16, 18, 20],
        soldiers: 8,
        owner: "player",
        headquarters: true,
        distanceFromComputerHQ: 6,
        distanceFromPlayerHQ: 0,
    },
    {
        id: 18,
        name: "תל אביב",
        x: 29.3,
        y: 57.3,
        neighbors: [15, 16, 17, 19],
        soldiers: 4,
        owner: "player",
        distanceFromComputerHQ: 6,
        distanceFromPlayerHQ: 1,
    },
    {
        id: 19,
        name: "באר שבע",
        x: 39.1,
        y: 71.6,
        neighbors: [18, 20, 21],
        soldiers: 4,
        owner: "player",
        distanceFromComputerHQ: 7,
        distanceFromPlayerHQ: 2,
    },
    {
        id: 20,
        name: "חברון",
        x: 48.8,
        y: 61.8,
        neighbors: [17, 19, 21],
        soldiers: 4,
        owner: "player",
        distanceFromComputerHQ: 7,
        distanceFromPlayerHQ: 1,
    },
    {
        id: 21,
        name: "אילת",
        x: 42.7,
        y: 98.7,
        neighbors: [19, 20],
        soldiers: 4,
        owner: "player",
        distanceFromComputerHQ: 8,
        distanceFromPlayerHQ: 2,
    },
];


